server:
  port: 8760                #指定该Eureka实例的端口 8761
eureka:
  instance:
    hostname: discovery    # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
# mysql路径，用户名、密码 以及驱动类
spring:
  datasource:
    url: jdbc:mysql://172.0.0.1:3306/my_blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wang123