server:
  port: 8001

#客户端名称
spring:
  application:
    name: hello-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1112/eureka/
  instance:
    instance-id: hello-service  #status前面的名字，（UP (1) - DESKTOP-TJD98J9:hello-service:8001 ==> UP (1) - hello-service）



#配置注册中心显示的注册信息
info:
  app.name: hello-service
  company.name: wangfj
  build.artifactId: $project.artifactId$
  build.version: $project.version$


